name: Veronica L Peterson
favicon: null
layout_spectrum: 0.76532
typography_spectrum: 0.51935
title: Veronica L Peterson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76788299-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#f3ffc0'
    - '#ff8678'
    - '#272623'
    - '#00e0c5'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
